languageCode = "en"
languageName = "English"
weight = 1
title = "Ashish"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
 # logo = "img/blowfish_logo_transparent.png"
 # description = "A powerful, lightweight theme for Hugo."

 [author]
   name = "Ashish Nath"
   image = "img/blowfish_logo.png"
   headline = "ReactJs / NextJs Developer"
   bio = "Web Developer"
   links = [
    { email = "mailto:ashishn401@gmail.com" },
    { discord = "https://discord.gg/K2WwR8nV" },
    { github = "https://github.com/ashish-nath" },
    { instagram = "https://instagram.com/_ashishnath_" },
    { linkedin = "https://www.linkedin.com/in/nathashish/" },
    { telegram = "https://t.me/ashishnath.me" },
   # { twitter = "https://twitter.com/username" },
    { x-twitter = "https://x.com/AshishNath401" },
   ]